[tool.black]
line-length = 79

[tool.pylint]
disable = [
    "invalid-name",
    "protected-access",
    "broad-except",
    "bare-except",
    "abstract-method",
    "duplicate-code",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-positional-arguments",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "unused-argument"
]

[tool.pylint.master]
reports = false